AWSTemplateFormatVersion: "2010-09-09"  
Description: Create an EC2 instance in your us-west-1 Default-VPC and Default-Subnet, attach a volume, run a webserver to host some content.

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  ## Security group for WebInstance enabling port 80
  ## from all IP addresses
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server
      GroupName: web
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ## EC2 Instance with a custom security group
  ## with an Amazon Linux 2 AMI in us-west-1 region
  ## and an externally created EBS volume with website content attached
  ## Userdata to install docker and host website content data via a nginx webserver
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-015954d5e5548d13b
      KeyName: !Ref KeyPairName
      InstanceType: t2.small
      AvailabilityZone: us-west-1a
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      Tags:
        -
          Key: Name
          Value: webserver
      Volumes:
        -
          Device: "/dev/xvdf"
          VolumeId: !Ref WebContent
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install git -y
          amazon-linux-extras install docker -y
          service docker start
          systemctl enable docker
          usermod -a -G docker ec2-user
          mkdir /data
          mount /dev/xvdf1 /data
          git clone https://github.com/dschulian/my-webserver.git /home/ec2-user/my-webserver
          cp -r /data/html /home/ec2-user/my-webserver/
          chown -R ec2-user:ec2-user /home/ec2-user/my-webserver/
          chmod -R +rw /home/ec2-user/my-webserver/html
          umount /data
          docker build -t my-webserver /home/ec2-user/my-webserver/
          docker run -dit --restart unless-stopped -p 80:80 my-webserver

  ## EBS Volume from a snapshot with website content data
  WebContent:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-west-1a
      Size: 1
      SnapshotId: snap-df75e5b5
      Tags:
        -
          Key: Name
          Value: webserver-content
      VolumeType: gp2
  
Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt WebInstance.PublicIp

  PublicDNS: 
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt WebInstance.PublicDnsName