AWSTemplateFormatVersion: "2010-09-09"  
Description: Create an EC2 instance, attach a volume, run a webserver to host some content.
Resources:

  ## Security group for WebInstance enabling port 80
  ## from all IP addresses
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server
      GroupName: web
      VpcId: vpc-2ff17a4a
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ## EC2 Instance with a custom security group
  ## and a larger root instance device
  ## and an externally created EBS volume attached
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-015954d5e5548d13b
      KeyName: my-key
      InstanceType: t2.small
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      SubnetId: subnet-c8318d91
      Tags:
        -
          Key: Name
          Value: webserver
      Volumes:
        -
          Device: "/dev/xvdf"
          VolumeId: !Ref WebContent
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install git -y
          amazon-linux-extras install docker -y
          service docker start
          systemctl enable docker
          usermod -a -G docker ec2-user
          mkdir /data
          mount /dev/xvdf1 /data
          git clone https://github.com/dschulian/my-webserver.git
          cp -r /data/html my-webserver/
          chown -R ec2-user:ec2-user my-webserver/
          chmod -R +rw my-webserver/html
          umount /data
          docker build -t my-webserver my-webserver/
          docker run -dit --restart unless-stopped -p 80:80 my-webserver

  ## EBS Volume for storing web logs
  WebContent:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-west-1a
      Size: 1
      SnapshotId: snap-df75e5b5
      Tags:
        -
          Key: Name
          Value: webserver-content
      VolumeType: gp2